backend:
  name: github
  repo: Bushykeys/Dom-Filmu
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: "https://bushybushbush.netlify.app"
logo_url: "/assets/dom_filmu-logo-poziome-rental.png"

collections:
  - name: "settings"
    label: "Settings"
    files:
      - name: "layout"
        label: "Layout"
        file: "data/settings.json"
        format: "json"
        fields:
          - label: "Products per row"
            name: "itemsPerRow"
            widget: "number"
            min: 2
            max: 5
            default: 4
          - label: "Category order"
            name: "categoryOrder"
            widget: "list"
            field: {label: "Category", name: "category", widget: "string"}

  - name: "products"
    label: "Products"
    label_singular: "Product"
    files:
      - name: "all"
        label: "Product list"
        file: "data/products.json"
        format: "json"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            summary: "{{fields.title}} — {{fields.price}}"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Price", name: "price", widget: "string", required: false}
              - label: "Category"
                name: "category"
                widget: "select"
                options:
                  - Kamery i aparaty
                  - Streaming
                  - Monitory
                  - Światło
                  - Nagrywanie dźwięku
                  - Stabilizacja
                  - Akcesoria
                  - Adaptery
                  - Obiektywy
              - {label: "Features / bullet list", name: "features", widget: "list", required: false}

